git:
  quiet: true
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest_cases==1.17.0
install:
  - pip install .[testing]
script: pytest
